name: Continuous Deployment

on:
  # 1️⃣ Automatically trigger after CI passes (only for main)
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

  # 2️⃣ Fallback: trigger on push (for non-main or if CI doesn’t exist)
  push:
    branches:
      - main
      - feature/**   # optional — allow testing on feature branches
      # - dev          # optional — allow dev environment deploys

  # 3️⃣ Manual trigger anytime
  workflow_dispatch:

jobs:
  deploy:
    # Only run auto-deploy if CI passed OR triggered manually/push
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test SSH connection to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: whoami

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/sentiment-mlops
            git pull origin main
            chmod +x ./deploy.sh
            ./deploy.sh
