name: Continuous Integration

on:
  push:
    branches:
      - main
      - feature/**  # allow testing
      
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      # ✅ Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ Cache model files (to avoid repeated S3 downloads)
      - name: Cache model files
        uses: actions/cache@v4
        with:
          path: ./models
          key: models-${{ runner.os }}-${{ hashFiles('app/utils.py') }}
          restore-keys: |
            models-${{ runner.os }}-

      # ✅ Configure AWS credentials (only needed for first-time model download)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run tests
        env:
          MODEL_CACHE_DIR: ./models
        run: make test
